# docker-compose.yml
version: "3"
services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
      #password
      - POSTGRES_DB=glee
    ports:
      - "5432:5432" #first one is local,second is docker port
